development:
  password: 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
  theme_id: "81046863961"
  store: cozy-glow.myshopify.com
  ignore_files:
    - config/settings_data.json
production:
  password: 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
  theme_id: "81064984665"
  store: cozy-glow.myshopify.com
  timeout: 1m
  #readonly: true
  ignore_files:
    - config/settings_data.json